# Generated by Django 5.1.2 on 2024-10-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='You can add hashtags here!', null=True, verbose_name='Project notes'),
        ),
    ]
