# Generated by Django 5.1.2 on 2024-10-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'categories'},
        ),
    ]
