# Generated by Django 5.0.6 on 2024-07-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notify_comment',
            field=models.BooleanField(default=True, verbose_name='Notify me when someone comments on my project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_like',
            field=models.BooleanField(default=True, verbose_name='Notify me when someone likes my project'),
        ),
    ]
