# Generated by Django 5.1.2 on 2024-11-22 16:31

from django.db import migrations


def fix_accounts(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("users", "User")
    EmailAddress = apps.get_model("account", "EmailAddress")
    for user in User.objects.filter(groups__name__in=['Puppets']):
        user.email = f"{user.username}@turtlestitch.org"
        user.notify_comment = False
        user.notify_like = False
        user.save()

        # add allauth email account
        EmailAddress.objects.filter(user=user).delete()
        new_account, created = EmailAddress.objects.get_or_create(
            user=user,
            email=user.email,
            primary = True,
            verified = True
        )
        # new_account.save() 

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_notify_comment_alter_user_notify_like'),
    ]

    operations = [
        migrations.RunPython(fix_accounts)
    ]
