# Generated by Django 5.1.2 on 2024-10-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
    ]
